title = "TOML Example"

# comment

ola = 1 # c omment endl
[owner]
name.apelido = "Tom Preston-Werner"
date = 2010-04-23
time = 21:30:00

[database]
server = "192.168.1.1"
ports.a.b = [ 8001, 8001, 8002]
ports.b = [ 8001, 8001, 8002]

connection_max = 5000
enabled = true

[servers]
[servers.alpha]
ip = "10.0.0.1"
dc = "eqdc10"

[servers.beta]
ip = "10.0.0.2"
dc = "eqdc10"

# Line breaks are OK when inside arrays

hosts = [
    "alpha",
    "omega"
]